# Use an official Node.js runtime as the base image
FROM node:14-alpine

# Set the working directory in the container
# assuming your app is located in C:\myapp\
C:\\Users\\Admin\\Documents\\work-completed\\backend\\node
# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm ci

# Copy the rest of the application's files
COPY . .

# Expose the port that the application will run on
EXPOSE 3000

# Run the application
CMD [ "npm", "start" ]
